# Generated by Django 5.0.6 on 2024-05-08 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voltasapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='washingmachine',
            table='WashingMachine',
        ),
    ]
