# Generated by Django 5.0.6 on 2024-05-08 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voltasapp', '0003_remove_washingmachine_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='washingmachines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3, null=True)),
                ('soldBy', models.CharField(max_length=255, null=True)),
                ('brand', models.CharField(max_length=255, null=True)),
                ('model', models.CharField(max_length=255, null=True)),
                ('capacity', models.CharField(max_length=50, null=True)),
                ('color', models.CharField(max_length=50, null=True)),
                ('asin', models.CharField(max_length=20, null=True)),
                ('genericname', models.CharField(max_length=50, null=True)),
                ('url', models.CharField(max_length=255, null=True)),
                ('energyEfficiency', models.CharField(max_length=50, null=True)),
                ('maximumRotationalSpeed', models.CharField(max_length=50, null=True)),
                ('noiseLevel', models.CharField(max_length=50, null=True)),
                ('installationType', models.CharField(max_length=50, null=True)),
                ('partNumber', models.CharField(max_length=50, null=True)),
                ('specialFeatures', models.TextField(null=True)),
                ('controlConsole', models.CharField(max_length=50, null=True)),
                ('numberOfStandardCycles', models.IntegerField(null=True)),
                ('accessLocation', models.CharField(max_length=50, null=True)),
                ('voltage', models.CharField(max_length=50, null=True)),
                ('certification', models.CharField(max_length=50, null=True)),
                ('material', models.CharField(max_length=50, null=True)),
                ('includedComponents', models.TextField(null=True)),
                ('batteriesRequired', models.CharField(max_length=5, null=True)),
                ('manufacturer', models.CharField(max_length=255, null=True)),
                ('countryOfOrigin', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'washingmachines',
            },
        ),
        migrations.DeleteModel(
            name='washingmachine',
        ),
    ]
