# Generated by Django 5.0.6 on 2024-05-08 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voltasapp', '0004_washingmachines_delete_washingmachine'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='washingmachines',
            new_name='washingmachine',
        ),
        migrations.AlterModelTable(
            name='washingmachine',
            table='washingmachine',
        ),
    ]
