# Generated by Django 5.0.6 on 2024-05-08 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voltasapp', '0005_rename_washingmachines_washingmachine_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sk', models.CharField(max_length=128, null=True, unique=True)),
                ('source_name', models.CharField(max_length=255, null=True)),
                ('source_id', models.IntegerField(null=True)),
                ('category', models.CharField(max_length=255, null=True)),
                ('product_name', models.TextField(null=True)),
                ('product_url', models.TextField(null=True)),
                ('mrp', models.TextField(null=True)),
                ('deal_price', models.TextField(null=True)),
                ('discount_percentage', models.CharField(max_length=255, null=True)),
                ('seller_name', models.CharField(max_length=255, null=True)),
                ('seller_name_and_id', models.TextField(null=True)),
                ('seller_address', models.TextField(null=True)),
                ('bank_offers', models.TextField(null=True)),
                ('offers', models.TextField(null=True)),
                ('brand', models.CharField(max_length=255, null=True)),
                ('model_name', models.TextField(null=True)),
                ('capacity', models.CharField(max_length=255, null=True)),
                ('colour', models.CharField(max_length=255, null=True)),
                ('technical_details', models.TextField(null=True)),
                ('seller_details', models.TextField(null=True)),
                ('seller_actual_name', models.TextField(null=True)),
                ('seller_id', models.CharField(max_length=255, null=True)),
                ('channel_sku', models.CharField(max_length=255, null=True)),
                ('channel', models.CharField(max_length=255, null=True)),
                ('model_number', models.CharField(max_length=255, null=True)),
                ('location', models.CharField(max_length=255, null=True)),
                ('zipcode', models.CharField(max_length=255, null=True)),
                ('mop_modified', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Product',
            },
        ),
        migrations.DeleteModel(
            name='washingmachine',
        ),
    ]
