# Generated by Django 5.0.6 on 2024-05-08 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voltasapp', '0007_alter_product_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='Product',
        ),
    ]
