# Generated by Django 5.0.6 on 2024-05-15 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voltasapp', '0010_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoltasProductDetails',
            fields=[
                ('model_name', models.CharField(max_length=100)),
                ('seller_name', models.CharField(max_length=100)),
                ('my_primary_key', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'voltas_product_details',
            },
        ),
    ]
