# Generated by Django 5.0.6 on 2024-05-15 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voltasapp', '0011_voltasproductdetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VoltasProductDetails',
        ),
    ]
