# Generated by Django 5.0.6 on 2024-05-29 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voltasapp', '0015_voltas_mapping_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='voltas_product_details',
            name='breach_amount',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='voltas_product_details',
            name='mop',
            field=models.TextField(null=True),
        ),
    ]
